// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdEddtx-LHRprXqNRwCKK_G49YKkf5AuI',
    appId: '1:14919420795:android:3535f4be33185462488bde',
    messagingSenderId: '14919420795',
    projectId: 'shop-app-a79db',
    storageBucket: 'shop-app-a79db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6STvWRTksdi5bFPNXFPUK5ty4BPc2ueM',
    appId: '1:14919420795:ios:bdfea9bd2b4580b1488bde',
    messagingSenderId: '14919420795',
    projectId: 'shop-app-a79db',
    storageBucket: 'shop-app-a79db.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWPMJd8RUNt96oEVVQ1CPMuIAQw2CnCU',
    appId: '1:14919420795:web:79a52e4210409291488bde',
    messagingSenderId: '14919420795',
    projectId: 'shop-app-a79db',
    authDomain: 'shop-app-a79db.firebaseapp.com',
    storageBucket: 'shop-app-a79db.appspot.com',
    measurementId: 'G-C4J0ZGCRFV',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZWPMJd8RUNt96oEVVQ1CPMuIAQw2CnCU',
    appId: '1:14919420795:web:cb7e0d426c909807488bde',
    messagingSenderId: '14919420795',
    projectId: 'shop-app-a79db',
    authDomain: 'shop-app-a79db.firebaseapp.com',
    storageBucket: 'shop-app-a79db.appspot.com',
    measurementId: 'G-K3J9HC3W8C',
  );

}